name: flutter_mic_platform
description: "A Flutter test project to make a cross-platform microphone using record, audioplayers, and flutter_riverpod packages."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  audioplayers: ^6.5.1
  flutter:
    sdk: flutter
  flutter_riverpod: 2.6.1
  path: ^1.9.1
  path_provider: ^2.1.5
  record: ^6.1.1
  web: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
