name: flutter_mic_platform
description: "An example Flutter project of a cross-platform microphone using record, audioplayers, and flutter_riverpod packages for iOS and web."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  audioplayers: ^6.5.1
  flutter_riverpod: 2.6.1
  path: ^1.9.1
  path_provider: ^2.1.5
  record: ^6.1.1
  web: ^1.1.1
  mime: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
